local var, three_var = "local b,a = pop(stack), pop(stack)\n","local c,b,a = pop(stack), pop(stack), pop(stack)\n"
return {
  op = {
      ["+"] = var.."stack[#stack+1] = a + b",
      ["-"] = var.."stack[#stack+1] = a - b",
      ["*"] = var.."stack[#stack+1] = a * b",
      ["/"] = var.."stack[#stack+1] = a / b",
      ["%"] = var.."stack[#stack+1] = a % b",
      ["="] = var.."stack[#stack+1] = a == b",
      [">"] = var.."stack[#stack+1] = a > b",
      ["<"] = var.."stack[#stack+1] = a < b",
      ["and"] = var.."stack[#stack+1] = a and b",
      ["or"] = var.."stack[#stack+1] = a or b",
      ["not"] = "stack[#stack+1] = not pop(stack)",
      ["."] = "print(pop(stack))",
      ["dump"] = "dump(false)",
      ["mem"] = "dump(true)",
      ["dup"] = "stack[#stack+1] = stack[#stack]",
      ["over"] = "stack[#stack+1] = stack[#stack - 1]",
      ["swap"] = "stack[#stack],stack[#stack - 1] = stack[#stack - 1], stack[#stack]",
      ["drop"] = "pop(stack)",
      ["do"] = "for i = pop(stack), pop(stack) - 1 do",
      ["i"] = "stack[#stack+1] = i",
      ["br"] = "break",
      ["begin"] = "repeat",
      ["until"] = "until pop(stack)",
      ["if"] = "if pop(stack) then",
      ["else"] = "else",
      [":"] = "function ",
      [";"] = "end",
      ["exec"] = "pop(stack)()",
      ["!"] = "mem[pop(stack)] = pop(stack)",
      ["@"] = "stack[#stack+1] = mem[pop(stack)]",
      ["read"] = "local r = io.open(pop(stack),'r')\nstack[#stack+1] = r:read('*a')\nr:close()",
      ["write"] = "local w = io.open(pop(stack),'w')\nw:write(pop(stack))\nw:close()",
      ["strin"] = "stack[#stack+1] = tostring(io.read())",
      ["numin"] = "stack[#stack+1] = tonumber(io.read())",
      ["cat"] = var.."stack[#stack+1] = tostring(a) .. tostring(b)",
      ["bi"] = three_var.."stack[#stack+1] = a\nb()\nstack[#stack+1] = a\nc()",
      ["cond"] = three_var.."if a then b() else c() end",
      ["times"] = var.."for i=1,a do b() end",
    },
  const_fold = {
    ["+"] = function(a, b) return a + b end,
    ["-"] = function(a, b) return a - b end,
    ["*"] = function(a, b) return a * b end,
    ["/"] = function(a, b) return a / b end,
    ["%"] = function(a, b) return a % b end,
    ["="] = function(a, b) return a == b end,
    [">"] = function(a, b) return a > b end,
    ["<"] = function(a, b) return a < b end,
    ["and"] = function(a, b) return a and b end,
    ["or"] = function(a, b) return a or b end,
    ["not"] = function(a) return not a end,
    ["cat"] = function(a, b)
      if type(a) == "string" and type(b) == "string" then return a .. b
      else return nil end
    end,
  }
}